version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-chat-server"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-165j3dfnswg4y"
s3_prefix = "sam-chat-server"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
