AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-chat-server

  Sample SAM Template for sam-chat-server

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  GetChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: chat/
      Handler: app.getChat
      Runtime: python3.8
      Policies: AWSLambdaFullAccess
      Events:
        GetChat:
          Type: Api
          Properties:
            Path: /chat
            Method: get
  PostChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: chat/
      Handler: app.postChat
      Runtime: python3.8
      Policies: AWSLambdaFullAccess
      Events:
        PostChat:
          Type: Api
          Properties:
            Path: /chat
            Method: post

  ChatDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: chat-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: user
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  GetChatApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/chat/"
  GetChatFunction:
    Value: !GetAtt GetChatFunction.Arn
  GetChatFunctionIamRole:
    Value: !GetAtt GetChatFunctionRole.Arn
  PostChatApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/chat/"
  PostChatFunction:
    Value: !GetAtt PostChatFunction.Arn
  PostChatFunctionIamRole:
    Value: !GetAtt PostChatFunctionRole.Arn